site_name: emmet-horgan
nav:
    - Blog:
      - blog/index.md
    - About me: index.md
    - Ciriculum Vitae: cv.md

theme: 
    name: material
    logo: assets/circle-album-inspired/logo.png
    favicon: assets/circle-album-inspired/favicon.ico
    icon:
      repo: fontawesome/brands/github
    font: 
        text: Roboto Mono
    palette:
        - media: "(prefers-color-scheme)"
          slate: grey
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to system preference

    features:
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.footer
        - content.code.annotate
        - content.code.copy
        - header.autohide
plugins: 
    - blog:
        categories: true
        draft: true
        blog_toc: true
        pagination_per_page: 5
    - search

markdown_extensions: 
    - pymdownx.arithmatex:
        generic: true
    - attr_list
    - md_in_html
    - tables
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
extra_javascript:
    - javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
    generator: false
    social:
        - icon: 'fontawesome/brands/github'
          link: 'https://github.com/emmet-horgan'
        - icon: 'fontawesome/brands/linkedin'
          link: 'https://www.linkedin.com/in/emmethorgan/'
    analytics:
        provider: google
        property: G-KQMYZCGPZX
repo_url: https://github.com/emmet-horgan/
repo_name: emmet-horgan

