name: ci
on: 
  push:
    branches:
      - master
      - main
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.137.0
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
      - name: Build
        run: hugo --minify
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          